// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isuhzunngcwlgfuzxvmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdWh6dW5uZ2N3bGdmdXp4dm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTg2MzMsImV4cCI6MjA2OTc5NDYzM30.q_TQ1pnUNDGGkwlrtLgwUovOMNHqhV3uj1JpBegEZQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});